# Generated by Django 5.2.1 on 2025-05-23 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderDate', models.DateTimeField(auto_now_add=True)),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50)),
                ('Supplier', models.CharField(blank=True, max_length=255, null=True)),
                ('ExpectedDeliveryDate', models.DateField(blank=True, null=True)),
                ('TotalAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PartName', models.CharField(max_length=255, unique=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('StockLevel', models.IntegerField(default=0)),
                ('ReorderPoint', models.IntegerField(blank=True, default=0, null=True)),
                ('Supplier', models.CharField(blank=True, max_length=255, null=True)),
                ('UnitPrice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('PriceAtOrder', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.order')),
                ('Part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.part')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShipmentDate', models.DateField(blank=True, null=True)),
                ('EstimatedDeliveryDate', models.DateField(blank=True, null=True)),
                ('ActualDeliveryDate', models.DateField(blank=True, null=True)),
                ('TrackingNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('Carrier', models.CharField(blank=True, max_length=100, null=True)),
                ('Status', models.CharField(choices=[('Preparing', 'Preparing'), ('InTransit', 'InTransit'), ('Delivered', 'Delivered'), ('Delayed', 'Delayed')], default='Preparing', max_length=50)),
                ('Order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
            ],
        ),
        migrations.CreateModel(
            name='StockKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateRecorded', models.DateField(auto_now_add=True)),
                ('Name', models.CharField(choices=[('StockTurnover', 'StockTurnover'), ('AverageStockValue', 'AverageStockValue'), ('OutOfStockRate', 'OutOfStockRate'), ('FillRate', 'FillRate')], max_length=100)),
                ('Value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Notes', models.TextField(blank=True, null=True)),
                ('Part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.part')),
            ],
        ),
    ]
